/* eslint-disable prettier/prettier */
/* eslint-disable semi */
const icon_close_eye = require('../assets/icons/icon_close_eye/icon_close_eye.png');
const icon_open_eye = require('../assets/icons/icon_open_eye/icon_open_eye.png');
const icon_email = require('../assets/icons/icon_email/icon_email.png');
const icon_lock = require('../assets/icons/icon_lock/icon_lock.png');
const icon_user = require('../assets/icons/icon_user/icon_user.png');
const icon_phone = require('../assets/icons/icon_phone/icon_phone.png');
const icon_state = require('../assets/icons/icon_state/icon_state.png');
const icon_city = require('../assets/icons/icon_city/icon_city.png');
const icon_zipcode = require('../assets/icons/icon_zipcode/icon_zipcode.png');
const icon_arrow_back = require('../assets/icons/icon_arrow_back/icon_arrow_back.png');
const icon_arrow_back1 = require('../assets/icons/icon_arrow_back1/icon_arrow_back1.png');
const icon_forgotpassword_lock = require('../assets/icons/icon_forgotpassword_lock/icon_forgotpassword_lock.png');
const icon_check_circle = require('../assets/icons/icon_check_circle/icon_check_circle.png');
const icon_circle_right = require('../assets/icons/icon_circle_right/icon_circle_right.png');
const icon_dropdown_circle = require('../assets/icons/icon_dropdown_circle/icon_dropdown_circle.png');
const icon_check_circle_green = require('../assets/icons/icon_check_circle_green/icon_check_circle_green.png');
const icon_ios_arrow_down = require('../assets/icons/icon_ios_arrow_down/icon_ios_arrow_down.png');
const icon_attach_file = require('../assets/icons/icon_attach_file/icon_attach_file.png');
export default { icon_attach_file, icon_ios_arrow_down, icon_check_circle_green, icon_arrow_back, icon_dropdown_circle, icon_circle_right, icon_check_circle, icon_forgotpassword_lock, icon_arrow_back1, icon_arrow_back, icon_zipcode, icon_city, icon_state, icon_close_eye, icon_open_eye, icon_email, icon_lock, icon_user, icon_phone };
