/* eslint-disable prettier/prettier */
/* eslint-disable semi */
const appBg = require('../assets/Images/app_bg/app_bg.png');
const img_animals = require('../assets/Images/img_animals/img_animals.png');
const logo_logly_splash = require('../assets/Images/logo_logly_splash/logo_logly_splash.png');
const img_login_header = require('../assets/Images/img_login_header/img_login_header.png');
const img_new_password = require('../assets/Images/img_new_password/img_new_password.png');
const img_fireworks = require('../assets/Images/img_fireworks/img_fireworks.png');
const img_btn_forward = require('../assets/Images/img_btn_forward/img_btn_forward.png');
const img_popup_services = require('../assets/Images/img_popup_services/img_popup_services.png');
const img_friend_sample = require('../assets/Images/img_friend_sample/img_friend_sample.png');
const img_activity = require('../assets/Images/img_activity/img_activity.png');
const img_donate = require('../assets/Images/img_donate/img_donate.png');
const img_pet_profile = require('../assets/Images/img_pet_profile/img_pet_profile.png');
const img_reg_pet = require('../assets/Images/img_reg_pet/img_reg_pet.png');
const img_inventory_home = require('../assets/Images/img_inventory_home/img_inventory_home.png');
const sample_bird = require('../assets/Images/sample_bird/sample_bird.png');
const img_bg_quickmenu = require('../assets/Images/img_bg_quickmenu/img_bg_quickmenu.png');
const bg_splash1 = require('../assets/Images/bg_splash1/bg_splash1.png');
const bg_splash2 = require('../assets/Images/bg_splash2/bg_splash2.png');
const bg_splash3 = require('../assets/Images/bg_splash3/bg_splash3.png');
const bg_splash4 = require('../assets/Images/bg_splash4/bg_splash4.png');
const img_logo_splash = require('../assets/Images/img_logo_splash/img_logo_splash.png');
const img_user_placeholder = require('../assets/Images/img_user_placeholder/img_user_placeholder.jpg');
export default { bg_splash4,img_user_placeholder,img_logo_splash,bg_splash1, bg_splash2,bg_splash3,img_bg_quickmenu,sample_bird,img_inventory_home,img_reg_pet,img_pet_profile,img_donate,img_activity,img_friend_sample,img_popup_services,img_btn_forward,img_fireworks, img_new_password, appBg, img_animals, logo_logly_splash, img_login_header };
